on:
  workflow_dispatch:
  pull_request:

name: "Test"
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Dev Container CLI
        run: |
          npm install -g @devcontainers/cli

      - name: Run tests
        run: |
          npx @devcontainers/cli features test
  shellcheck:
    name: Test
    uses: ./.github/workflows/check.yml